name: deer
description: Minimalist Todo Planner app built around the idea of efficiency and clean aesthetic.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.4+13
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # stream
  rxdart: ^0.28.0

  # value
  built_value: ^8.9.5
  built_collection: ^5.1.1
  collection: ^1.19.1

  # notification
  flutter_local_notifications: ^19.2.0

  # images
  image_picker: ^1.1.2
  photo_view: ^0.15.0

  # calendar
  table_calendar: ^3.2.0

  # url
  link_text: ^0.2.1

  # gestures
  simple_gesture_detector: ^0.2.1

  # carousel
  flutter_swiper: ^1.1.6

  # platform
  shared_preferences: ^2.5.3
  keyboard_visibility: ^0.5.6

  # util
  tuple: ^2.0.2

dependency_overrides:
  analyzer: 7.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  built_value_generator: ^8.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
